### ISSUE TITLE
Create Task Assignment

### ISSUE THREAD

**Issue by jonesabby** [fastruby/harvesting#37]
The path to create a task_assigment is POST /v2/projects/{PROJECT_ID}/task_assignments - current create method on the client does not work to create a task_assignment. Unable to assign a task to a project.

**Comment by etagwerker** [comment]
@jonesabby what error do you get? could you share the backtrace with us?

**Comment by bronzdoc** [comment]
Closing due to lack of response. But willreopen if we get a backtrace @jonesabby thanks
