### ISSUE TITLE
Add Clients < HarvestRecordCollection to harvesting/lib/harvesting/models/

### ISSUE THREAD

**Issue by kimonoso** [fastruby/harvesting#42]
Hi Ombulabs,

First time doing this so my apologies if the way I write is inconvenient.

Can you add a clients.rb in the models with inheritance from HarvestRecordCollection?

I noticed that Harvesting isn't getting all of the clients. I only had 100 results when my account has 400+ clients. Also, it isn't taking any options such as (is_active: true). I got the expected 0 arguments error.

I investigated on the gem source code (first time also) and noticed that there are no clients.rb model with an inheritance from HarvestRecordCollection. The code really doesn't allow for any options to be placed.

My current work-around to it is to modify the gem (first time again). However, the function Harvest::client.new(credentials).clients was 20x slower. So, I'm not really sure how to work on this now.

Can you add this up?

Thanks!

**Comment by etagwerker** [comment]
@kimonoso I think that this has been added with this PR: https://github.com/ombulabs/harvesting/pull/39

Could you confirm?
