### ISSUE TITLE
Rails support

### ISSUE THREAD

**Issue by nardonykolyszyn** [fastruby/harvesting#52]
Hi guys! Love your company.

I forked the project and added Rails support by creating a custom generator to ease gem configuration, are you open to receive a new PR? The approach is inspired in Heartcombo devise and simple_form intention.

So the generator looks like this:

```ruby
$ rails g harvesting:install
```

Tests are covered too via minitets but I can add rspec support.

**Comment by bronzdoc** [comment]
Hey @nardonykolyszyn!

Thanks so much for your kind words and taking the time to contribute 🙂 

Please submit a PR with your changes and one of us will review it!

**Comment by nardonykolyszyn** [comment]
Just created a new [PR here](https://github.com/fastruby/harvesting/pull/53), however some tests are failing due I replaced instance accessors with class variables accessors. Are you guys willing to change this or definitely you want to keep traditional accessors? If you decide to change them, I can fix existing tests. 🛠
