### ISSUE TITLE
Is there a release version of `harvesting` with Ruby 3.0 support?

### ISSUE THREAD

**Issue by smaboshe** [fastruby/harvesting#75]
Thanks for this gem!

From the [release notes](https://github.com/fastruby/harvesting/blob/main/RELEASE_NOTES.md), Ruby 3.0 is now supported. Is there a released version available as well now?

**Comment by smaboshe** [comment]
Hope you are well. Just checking in to see if there is a timeline to cut a release of the current version of `harvesting`.

**Comment by etagwerker** [comment]
@smaboshe I just published a new release over here: https://rubygems.org/gems/harvesting/versions/0.6.0

**Comment by smaboshe** [comment]
Thank you, @etagwerker!
